services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    env_file:
      - ./.env
    ports:
      - "3000:80"
    restart: unless-stopped
