services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    # If your frontend performs API calls to the backend, ensure it points to http://backend:8080
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped
