services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    restart: unless-stopped
