services:
  python-pdf-server:
    container_name: python-pdf-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: ${PORT:-8000}
    ports:
      - "${PORT:-8000}:8000"
    restart: unless-stopped
