/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemesGuideRouteImport } from './routes/themes-guide'
import { Route as HtmlInterpreterStandardRouteImport } from './routes/html-interpreter-standard'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as IndexRouteImport } from './routes/index'

const ThemesGuideRoute = ThemesGuideRouteImport.update({
  id: '/themes-guide',
  path: '/themes-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HtmlInterpreterStandardRoute = HtmlInterpreterStandardRouteImport.update({
  id: '/html-interpreter-standard',
  path: '/html-interpreter-standard',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/html-interpreter-standard': typeof HtmlInterpreterStandardRoute
  '/themes-guide': typeof ThemesGuideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/html-interpreter-standard': typeof HtmlInterpreterStandardRoute
  '/themes-guide': typeof ThemesGuideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/html-interpreter-standard': typeof HtmlInterpreterStandardRoute
  '/themes-guide': typeof ThemesGuideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor' | '/html-interpreter-standard' | '/themes-guide'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor' | '/html-interpreter-standard' | '/themes-guide'
  id:
    | '__root__'
    | '/'
    | '/editor'
    | '/html-interpreter-standard'
    | '/themes-guide'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRoute
  HtmlInterpreterStandardRoute: typeof HtmlInterpreterStandardRoute
  ThemesGuideRoute: typeof ThemesGuideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/themes-guide': {
      id: '/themes-guide'
      path: '/themes-guide'
      fullPath: '/themes-guide'
      preLoaderRoute: typeof ThemesGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/html-interpreter-standard': {
      id: '/html-interpreter-standard'
      path: '/html-interpreter-standard'
      fullPath: '/html-interpreter-standard'
      preLoaderRoute: typeof HtmlInterpreterStandardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRoute,
  HtmlInterpreterStandardRoute: HtmlInterpreterStandardRoute,
  ThemesGuideRoute: ThemesGuideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
