/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GistDemoRouteImport } from './routes/gist-demo'
import { Route as IndexRouteImport } from './routes/index'

const GistDemoRoute = GistDemoRouteImport.update({
  id: '/gist-demo',
  path: '/gist-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gist-demo': typeof GistDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gist-demo': typeof GistDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gist-demo': typeof GistDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gist-demo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gist-demo'
  id: '__root__' | '/' | '/gist-demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GistDemoRoute: typeof GistDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gist-demo': {
      id: '/gist-demo'
      path: '/gist-demo'
      fullPath: '/gist-demo'
      preLoaderRoute: typeof GistDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GistDemoRoute: GistDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
