spring:
  application:
    name: backend

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/json2resume
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

# Logging Configuration
logging:
  level:
    com.example.backend: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
